config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "dashboard#index"
  resources :dashboard, only: :index
  post "payment", to: "payment#create", as: "payment"
  post "subcriptions", to: "subcriptions#create", as: "subcriptions"
  post "stripe_ipn", to: "stripe_ipn#create", as: "stripe_ipn"
  get "payments/success", to: "stripes/success#index", as: "payments/success"
  get "payments/cancel", to: "stripes/cancel#index", as: "payments/cancel"
  resources :invoices, only: :index
  post "refunds", to: "refunds#create", as: "refunds"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :serviceable, polymorphic: true

  enum status: [:no_invoice_due, :unpaid, :paid, :refuning, :refuned, :cancel]

  scope :newest, -> { order created_at: :desc }
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :invoices, as: :serviceable
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :invoices
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.newest
  end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  before_action :load_product, :load_invoice, only: :create

  def create
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    token = params[:token]

    begin
      if @invoice
        @invoice.no_invoice_due!
      else
        @invoice = @product.invoices.create(
          price: (@product.price * 100),
          status: :no_invoice_due,
          name: @product.name
        )
      end

      charge = Stripe::Charge.create(
        :amount => @product.price.to_i * 100,
        :currency => "usd",
        :source => token,
        :description => "Payment for #{@product.name}",
        :metadata => {
          invoice_id: @invoice.id
        }
      )

      redirect_to payments_success_path
    rescue Stripe::CardError => e
      @product.invoices.create(
        price: (@product.price * 100),
        status: :cancel
      )
      redirect_to payments_cancel_path
    end
  end

  private
  def load_product
    @product = Product.find_by id: params[:product_id]
  end

  def load_invoice
    @invoice = Invoice.find_by id: params[:invoice_id]
  end
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  before_action :load_invoice, only: :create

  def create
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]

    refund = Stripe::Refund.create({
      charge: @invoice.charge_id
    })

    if refund.status = "succeeded" && refund.object == "refund"
      @invoice.refuning!
      flash.now[:success] = "Refund payment is processing"
    else
      flash.now[:success] = "Refund payment is failed"
    end
  rescue
    flash.now[:success] = "Refund payment is failed"
  end

  private
  def load_invoice
    @invoice = Invoice.find_by id: params[:invoice_id]
  end
end

app/controllers/stripe_ipn_controller.rb
class StripeIpnController < ApplicationController
  protect_from_forgery except: :create
  skip_before_action :verify_authenticity_token, only: :create
  before_action :authenticate_user!, except: :create


  def create
    event = Stripe::Event.retrieve params[:id]

    case
    when event.type == "charge.refunded"
      ipn_refund event
    when event.type == "charge.succeeded"
      ipn_charge event
    when event.type == "invoice.payment_succeeded"
      ipn_subscription event
    end

    render nothing: true
  end

  private
  def ipn_charge event
    unless event.data.object.metadata.to_h.blank?
      invoice = Invoice.find_by id: event.data.object.metadata.invoice_id
      if event.data.object.paid
        # Xác nhận thanh toán thành công
        # create invoice
        invoice.update_attributes charge_id: event.data.object.id, status: :paid
      else
        # Xác nhận thanh thoán không thành công
        # Ta gửi email thông báo cho user
        invoice.update_attributes charge_id: event.data.object.id, status: :unpaid
      end
    end
  end

  def ipn_refund event
    unless event.data.object.metadata.to_h.blank?
      invoice = Invoice.find_by id: event.data.object.metadata.invoice_id
      if event.data.object.paid
        invoice.update_attributes status: :refuned, reason: "Requested by Customer"
      else
        invoice.update_attributes reason: "Refund fails. Please try again", status: :paid
      end
    end
  end

  def ipn_subscription event
    invoice = Invoice.find_by id: event.data.object.lines.data.first.metadata.invoice_id
    if event.data.object.paid
      invoice.update_attributes status: :paid, charge_id: event.data.object.id
    else
      invoice.update_attributes status: :unpaid, charge_id: event.data.object.id
    end
  end
end

app/controllers/stripes/cancel_controller.rb
class Stripes::CancelController < ApplicationController
  def index; end
end

app/controllers/stripes/success_controller.rb
class Stripes::SuccessController < ApplicationController
  def index; end
end

app/controllers/subcriptions_controller.rb
class SubcriptionsController < ApplicationController
  before_action :load_plan, only: :create

  def create
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    token = params[:token]
    info = Stripe::Token.retrieve(token)

    customer = Stripe::Customer.create(
      source: token,
      email: info.email
    )

    @invoice = @plan.invoices.create price: @plan.price, status: :no_invoice_due, name: @plan.name

    Stripe::Subscription.create(
      :customer => customer.id,
      :metadata => {
        invoice_id: @invoice.id
      },
      :items => [
        { plan: @plan.plan_stripe_id }
      ]
    )

    redirect_to payments_success_path
  rescue
    @plan.invoices.create(
      price: (@plan.price * 100),
      status: :cancel
    )
    redirect_to payments_cancel_path
  end

  private
  def load_plan
    @plan = Plan.find_by id: params[:plan_id]
  end

  def get_token_info
    info = Stripe::Token.retrieve(token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def message_alert_type type
    type == "danger" ? "alert alert-danger" : "alert alert-success"
  end
end

app/helpers/invoice_helper.rb
module InvoiceHelper
  def generate_status status
    case status
    when :paid
      "btn btn-success btn-sm"
    when :unpaid
      "btn btn-secondary btn-sm"
    when :refuned
      "btn btn-warning btn-sm"
    when :cancel
      "btn btn-danger btn-sm"
    when :refuning
      "btn btn-info btn-sm"
    else
      "btn btn-dark btn-sm"
    end
  end
end

app/views/dashboard/index.html.erb
<div class="jumbotron">
  <% @products.limit(6).each do |product| %>
    <div class="card" style="width: 16rem;">
      <img src="http://via.placeholder.com/286x180" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text"><%= number_to_currency(product.price, precision: 0) %></p>
        <div class="button_pay d-flex justify-content-center">
          <a href="#" class="btn btn-primary" id="stripe-credit-button"
            data-price="<%= product.price %>" data-id="<%= product.id %>">
            Payment
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="jumbotron subscription">
  <% Plan.all.each do |plan| %>
    <div class="card" style="width: 16rem;">
      <img src="http://via.placeholder.com/286x180" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title"><%= plan.name %></h5>
        <p class="card-text"><%= number_to_currency(plan.price.to_f, precision: 0) %></p>
        <div class="button_pay d-flex justify-content-center">
          <a href="#" class="btn btn-info" id="stripe-credit-button-subscription"
            data-price="<%= plan.price %>" data-id="<%= plan.id %>" data-name="<%= plan.name %>">
            <%= "Pay #{number_to_currency(plan.price.to_f, precision: 0)} per / #{plan.interval}"%>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

<style>
  .jumbotron {
    display: flex;
    flex-wrap: wrap;
    margin-top: 20px;
    justify-content: space-between;
  }

  .subscription {
    justify-content: start;
  }

  .jumbotron .card {
    margin: 10px;
  }
</style>


<script>
  function stripe_checkout(product_id = null) {
    var handler = StripeCheckout.configure({
      key: "<%= ENV["STRIPE_PUBLIC_KEY"]%>",
      //image: '/img/documentation/checkout/marketplace.png',
      locale: "auto",
      token: function (token) {
        $.ajax({
          method: "POST",
          beforeSend: function (xhr) {
            xhr.setRequestHeader("X-CSRF-Token", $("meta[name='csrf-token']").attr("content"));
          },
          url: "<%= payment_path() %>",
          data: {
            token: token.id,
            product_id: product_id
          }
        });
      }
    });

    return handler;
  }

  $(document).on("click", "#stripe-credit-button", function (e) {
    var price = $(this).data("price");
    var product_id = $(this).data("id");

    handler = stripe_checkout(product_id);
    handler.open({
      name: "Stripe Demo",
      description: "Demo payment",
      amount: price * 100
    });
    e.preventDefault();
  });

  $(window).on("popstate", function () {
    handler = stripe_checkout();
    handler.close();
  });
</script>

app/views/invoices/index.html.erb
<table class="table table-striped" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Plan</th>
      <th scope="col">Price</th>
      <th scope="col">Status</th>
      <th scope="col">Reason</th>
      <th scope="col" style="width: 15%"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= "##{invoice.id}" %></th>
        <td><%= invoice.name %></td>
        <td><%= invoice.serviceable_type %></td>
        <td><%= number_to_currency(invoice.price / 100, precision: 0) %></td>
        <td>
          <span class="<%= generate_status(invoice.status.to_sym) %>"><%= invoice.status.titleize %></span>
        </td>
        <td><%= invoice.reason %></td>
        <td style="text-align: center">
          <% if invoice.no_invoice_due? || invoice.unpaid? || invoice.cancel? %>
            <button type="button" id="re_payment" data-id="<%= invoice.id %>"
              data-product-id="<%= invoice.serviceable_id %>" data-price="<%= invoice.price %>"
              class="btn btn-outline-success btn-sm">
              Re-Payment
            </button>
          <% end %>
          <% if invoice.paid? %>
            <button type="button" id="refund" data-id="<%= invoice.id %>" class="btn btn-outline-danger btn-sm">Refund</button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoStripe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://checkout.stripe.com/v3/checkout.js"></script>
  </head>

  <body>
    <div class="container-fluid">
      <% if user_signed_in? %>
        <%= render "shared/nav" %>
      <% end %>

      <% flash.each do |message_type, message| %>
        <div class="<%= message_alert_type message_type %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-top: 10px;">
  <a class="navbar-brand" href="/">
    <%= image_tag "stripe.svg", style: "width: 80px" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/invoices">Invoices</a>
      </li>
    </div>
    <div class="form-inline my-2 my-lg-0">
      Wellcome back:
      <% if user_signed_in? %>
        <label style="margin-right: 20px; font-weight: 600; margin-left: 10px;"><%= current_user.email %></label>
      <% end %>
      <a href="<%= destroy_user_session_path %>" data-method="delete">Logout</a>
    </div>
  </div>
</nav>

app/views/stripes/cancel/index.html.erb
<div class="jumbotron" style="margin-top: 20px;">
  Your are payment is failed. Please check information card
</div>

app/views/stripes/success/index.html.erb
<div class="jumbotron" style="margin-top: 20px;">
  Your are payment is successfully. An email confirm payment and billing is sent to your email
</div>